### ISSUE TITLE
Issue with options being set to last value when making multiple requests in quick succession

### ISSUE THREAD

**Issue by jon64digital** [bestander/gulp-deploy-azure-cdn#5] opened 2016-01-18 00:04 UTC
Hi,

I am trying to pipe two sets of files into deployCdn() in quick succession (so two separate calls). I am sending different options with both calls but because the first call hasn't finished when the options are set the second time, both are using the second set of options.

I think this is because "var options" is declared directly inside your module.exports so it's global in the sense that the variable's scope is not local to each call. When the second call is made the global options variable is overwritten and the first call which hasn't finished yet uses these options. Basically it's a race condition that always loses.

This doesn't seem an easy thing to fix and I notice that this is quite an old project so my solution is to use a single container and one set of options for all my files for now. I just thought you might like to know.

Jon

**Comment by jon64digital** [comment] 2016-01-18 02:23
For anybody else reading this I manage to get round this by running any deploy tasks which require different settings to run in series, waiting for the previous one to finish before starting the next one. I achieved this in my gulpfile.js by using the node async module like this...

    gulp.task('azureDeploy', function(callback) {
  
        var streams = [];
        var itemOption = {}        // options just for this deployment

	azureDeployFiles.forEach(function(item) {
            
            streams.push(
                function (next) {
                    gulp.src(item.src)
                        .pipe(deployCdn(itemOptions).on('error', gutil.log))
                        .on('end', function(){
                            next()
                        });
                }
            );

        });
        
        async.series(streams, callback);

    });

**Comment by bestander** [comment] 2016-01-18 10:25
Hey, @jon64digital.

Thanks for pointing this out.
The library is old but it is still loved and used in a few production systems.

I think the issue is in this repo https://github.com/bestander/deploy-azure-cdn.
I'll copy the issue.
Would you want to start a PR?

**Comment by bestander** [comment] 2016-01-18 10:27
I'll close this one because the fix will be coming to core component

**Closed by bestander** 2016-01-18 10:27 UTC
